<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div id="my-modal" class="modal">
    <span id="close-modal-icon" class="icon-arrow-down modal__close-icon"></span>
    <div class="modal__content">
        <div class="modal__image">
           <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('modal-image-block')->toHtml(); ?>
        </div>
        <div class="modal__info">
            <h2 class="modal__title"> Join the GlobeWest Family</h2>
            <p class="modal__text">Subscribe to our upcoming trends and directions, product news, interviews and home tours and special offers from our team.</p>
            <form class="modal__form">
                <div class="modal__form-group">
                    <?= $block->getChildHtml('custom.modal.newsletter'); ?>
                </div>
            </form>
            <div class="modal__actions">
                <span class="modal__close-btn">NO THANKS, CLOSE</span>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#my-modal": {
            "Magento_Theme/js/custom-modal": {}
        }
    }
</script>
